"""
Apply a TED edit script (diff JSON) to a source tree to reconstruct the target tree.

Supports the diff format generated by ted_edit_script.py:
- ops with kind in {INS, DEL, UPD}
- path: parent path (e.g., "/country/religion")
- old/new: labels
- node_is_leaf: bool
- subtree: full subtree snapshot for INS/DEL/UPD
"""

from __future__ import annotations

import argparse
import copy
import json
from pathlib import Path
from typing import Dict, List, Optional


def load_tree(path: Path) -> Dict:
    return json.loads(path.read_text(encoding="utf-8"))["tree"]


def save_tree(tree: Dict, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {"tree": tree}
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def path_parts(path: str) -> List[str]:
    return [p for p in path.split("/") if p]


def find_node(root: Dict, path: str) -> Optional[Dict]:
    if path in ("", "/"):
        return root
    parts = path_parts(path)
    cur = root
    for p in parts[1:]:  # skip leading "country"
        found = None
        for ch in cur.get("children", []):
            if ch.get("label") == p:
                found = ch
                break
        if found is None:
            return None
        cur = found
    return cur


def delete_child(parent: Dict, label: str) -> bool:
    children = parent.get("children", [])
    for i, ch in enumerate(children):
        if ch.get("label") == label:
            del children[i]
            return True
    return False


def insert_child(parent: Dict, subtree: Dict):
    parent.setdefault("children", []).append(copy.deepcopy(subtree))


def apply_ops(tree: Dict, ops: List[Dict]) -> Dict:
    # Apply in phases: DEL, INS, UPD
    del_ops = [o for o in ops if o["kind"] == "DEL"]
    ins_ops = [o for o in ops if o["kind"] == "INS"]
    upd_ops = [o for o in ops if o["kind"] == "UPD"]

    # Deletes
    for op in del_ops:
        parent = find_node(tree, op["path"])
        if not parent:
            continue
        delete_child(parent, op["old"])

    # Inserts
    for op in ins_ops:
        parent = find_node(tree, op["path"])
        if not parent:
            continue
        subtree = op.get("subtree") or {"label": op["new"], "children": []}
        insert_child(parent, subtree)

    # Updates (leaf value change)
    for op in upd_ops:
        parent = find_node(tree, op["path"])
        if not parent:
            continue
        for ch in parent.get("children", []):
            if ch.get("label") == op["old"]:
                ch["label"] = op["new"]
                break

    return tree


def main():
    parser = argparse.ArgumentParser(description="Apply a diff JSON to patch a source tree.")
    parser.add_argument("--source", required=True, type=Path, help="Source tree JSON (tokenized).")
    parser.add_argument("--diff", required=True, type=Path, help="Diff JSON produced by ted_edit_script.py.")
    parser.add_argument("--out", required=True, type=Path, help="Output patched tree JSON path.")
    args = parser.parse_args()

    src_tree = load_tree(args.source)
    diff = json.loads(args.diff.read_text(encoding="utf-8"))
    ops = diff.get("operations", [])

    patched = apply_ops(src_tree, ops)
    save_tree(patched, args.out)

    print(f"Patched tree written to {args.out}")
    print(f"Ops applied: {len(ops)}")


if __name__ == "__main__":
    main()
